server:
  port: 8086

spring:
  application:
    name: account
  # 数据源配置
  datasource:
    url: jdbc:mysql://dev.tss.com:3306/njit_account?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

# MyBatis配置
mybatis:
  mapper-locations: classpath:com/tss/account/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/